# Generated by Django 3.2.9 on 2021-11-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_group_id', models.CharField(max_length=50, verbose_name='Control Group ID')),
                ('control_group_title', models.CharField(max_length=50)),
                ('control_group_description', models.TextField()),
                ('control_item_id', models.CharField(max_length=15, verbose_name='Control Item ID')),
                ('control_item_title', models.CharField(max_length=100)),
                ('control_item_description', models.TextField()),
                ('recommended_evidence', models.TextField()),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.framework')),
            ],
        ),
    ]
