# Generated by Django 3.2.9 on 2021-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_group_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='control',
            name='control_item_title',
            field=models.TextField(),
        ),
    ]
