# Generated by Django 3.2.9 on 2021-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20211118_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_group_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='recommended_evidence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
