# Generated by Django 3.2.9 on 2021-11-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='BusinessUnit',
            new_name='business_unit',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='Organization',
            new_name='organization',
        ),
    ]
