# Generated by Django 3.2.9 on 2021-11-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_auto_20211118_1542'),
        ('program', '0002_auto_20211118_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='frameworks',
            field=models.ManyToManyField(to='framework.Framework'),
        ),
    ]
