# Generated by Django 3.2.9 on 2021-11-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
    ]
