# Generated by Django 3.2.9 on 2021-11-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.CharField(default='temp@temp.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(default='Temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_number',
            field=models.CharField(default='1234567890', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
