# Generated by Django 3.2.9 on 2021-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20211118_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdparty',
            options={'verbose_name_plural': 'third parties'},
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
    ]
