# Generated by Django 3.2.9 on 2021-11-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='organizations',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.contact'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.contact'),
        ),
    ]
