# Generated by Django 3.2.9 on 2021-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20211118_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
    ]
